### PR TITLE
Fix some Doxygen issues

### LINKED ISSUE #99: Doxygen docs are partially broken
It seems that the latest few PRs have broken the doxygen output for some of the library, including nearly the entirety of Manifold.h. It seems that the main issue is the usage of <> characters which I use for arrows and are used by C++ for template arguments but Doxygen treats them as HTML tags (despite us not using HTML tags anywhere in the documentation). More irritatingly, this does not seem to cause any errors or even warnings when building the documentation.

I will clean up the Doxyfile and try to resolve these problems. Unfortunately, I don't have any good ideas on how to prevent these issues in the future due to Doxygen silently failing while building the docs.

### PR DESCRIPTION
**Pull request by cakarsubasi**
Resolves #99.

This fixes some of the documentation issues introduced by the latest few PRs. It also fixes some miscellaneous issues I noticed in the meantime.

I also updated the Doxyfile to the newest version. I have added filters so files under demo and test should be excluded. I have also excluded items in namespace *::detail::* to be hidden.

I have also manually filtered the following files since it seemed like they probably should not be in the public docs:
                         - glxew.h
                         - wglew.h
                         - image_DXT.h
                         - stbi_DDS_aug_c.h
                         - stb_image.h

There are quite a few remaining issues:
- Since RsR is not in its own namespace, it pollutes the top namespace (as well as ETF and Treap)
- The mainpage needs to be updated to reflect the current state of the library.
- The discoverability through the docs needs to be improved. A simple way to use it is to use \defgroup to create topic pages, and then add related functionality to the group using \ingroup. 
- Hide private items from the public docs.

This is by no means comprehensive, but it should be an improvement compared to before.

### CODE REVIEW

File: src/GEL/HMesh/Manifold.h [hunk 1]
```diff
@@ -51,10 +53,11 @@ namespace HMesh
         VertexAttributeVector<Vec>& positions_attribute_vector();
         /// Return a const reference to the entire positions attribute vector (not recommended)
         const VertexAttributeVector<Vec>& positions_attribute_vector() const;
-        
-        // Constructor, housekeeping --------------------------------------------------
 
-        /// Default constructor (copy constructor is created automatically)
+        /// @name Constructor, housekeeping
```
Comment (cakarsubasi) [inline src/GEL/HMesh/Manifold.h:57]: \name can be used to create anonymous groups.

File: src/gel.dox [hunk 2]
```diff
@@ -99,50 +99,14 @@ There is also SOIL, the image loading library for OpenGL, by Jonathan Dummer.
...
+		Apart from Manifold there are also face and vertex circulators in this
+		namespace.
 
 		Some applications are also found here. For instance an isosurface 
 		polygonizer and Garland Heckbert simplification has been implemented
 	  on top of HMesh.
 */
 
-/*!
-	\namespace LinAlg
```
Comment (cakarsubasi) [inline src/gel.dox:111]: LinAlg seems to be long removed from GEL so I removed this, although mainpage likely needs further edits.

File: src/gel.dox [hunk 3]
```diff
@@ -99,50 +99,14 @@ There is also SOIL, the image loading library for OpenGL, by Jonathan Dummer.
 		\brief The HMesh namespace contains the Manifold class which is a halfedge
 		based mesh.
 
-		Apart from manifold there are also face and vertex circulators in this 
-		namespace. More advanced things are relegated to the HMeshUtil namespace.
```
Comment (cakarsubasi) [inline src/gel.dox:103]: HMeshUtil is also absent from GEL.

**Comment by janba** [comment]
Thanks!
